import {
  BadgeDollarSign,
  Bolt,
  BookOpen,
  Briefcase,
  Brush,
  Calculator,
  Camera,
  Dumbbell,
  Gavel,
  HardHat,
  Heart,
  LampFloor,
  Languages,
  Megaphone,
  Monitor,
  Music,
  Scissors,
  Scroll,
  Shirt,
  Truck,
  User,
  Utensils,
  Wrench,
} from "lucide-react";

export const CATEGORIES = {
  domestic: "domésticos",
  electrical: "elétrico",
  maintenance: "manutenção",
  administration: "administração",
  consulting: "consultoria",
  accounting: "contabilidade",
  design: "design",
  engineering: "engenharia",
  legal: "jurídico",
  marketing: "marketing",
  health: "saúde",
  technology: "tecnologia",
  transportation: "transporte",
  sales: "vendas",
  photography: "fotografia",
  music: "música",
  education: "educação",
  languages: "idiomas",
  sports: "esportes",
  culinary: "culinária",
  beauty: "beleza",
  fashion: "moda",
  crafts: "artesanato",
};

export const ICONS_CATEGORIES: Record<string, React.ElementType> = {
  LampFloor,
  Bolt,
  Wrench,
  Briefcase,
  User,
  Calculator,
  Brush,
  HardHat,
  Scroll,
  Megaphone,
  Gavel,
  Heart,
  Monitor,
  Truck,
  BadgeDollarSign,
  Camera,
  Music,
  BookOpen,
  Languages,
  Dumbbell,
  Utensils,
  Scissors,
  Shirt,
};
