export const CATEGORIES = {
  domestic: "domésticos",
  electrical: "elétrico",
  maintenance: "manutenção",
  administration: "administração",
  consulting: "consultoria",
  accounting: "contabilidade",
  design: "design",
  engineering: "engenharia",
  legal: "jurídico",
  marketing: "marketing",
  health: "saúde",
  technology: "tecnologia",
  transportation: "transporte",
  sales: "vendas",
  photography: "fotografia",
  music: "música",
  education: "educação",
  languages: "idiomas",
  sports: "esportes",
  culinary: "culinária",
  beauty: "beleza",
  fashion: "moda",
  crafts: "artesanato",
};
